In [42]:
#ubah citra yang berbentuk matriks menjaid vector berdimensi 12000
import cv2
import numpy as np
import glob

foto = glob.glob('gabung/*')
foto_mtr = np.array([np.array(cv2.imread(i,0)) for i in foto]).astype(float)

print(foto_mtr)

[[[ 60.  60.  62. ...  43.  52.  46.]
  [ 59.  70.  59. ...  38.  50.  50.]
  [ 66.  75.  76. ...  38.  50.  49.]
  ...
  [ 28. 126. 158. ...  34.  33.  33.]
  [ 22. 117. 157. ...  35.  35.  31.]
  [ 13.  99. 158. ...  32.  34.  34.]]

 [[216. 216. 216. ... 236. 236. 237.]
  [216. 216. 216. ... 236. 236. 237.]
  [216. 216. 216. ... 236. 236. 237.]
  ...
  [227. 227. 228. ... 254. 253. 253.]
  [227. 227. 228. ... 253. 253. 252.]
  [227. 227. 228. ... 253. 252. 252.]]

 [[ 71.  72.  73. ...  81.  79.  78.]
  [ 72.  74.  73. ...  83.  82.  81.]
  [ 75.  75.  76. ...  86.  84.  83.]
  ...
  [ 12.  11.  11. ...  12.  14.  15.]
  [ 11.  11.  10. ...  12.  13.  15.]
  [ 11.  11.  11. ...  12.  13.  14.]]

 ...

 [[120.  91. 109. ... 154. 149. 153.]
  [115. 100. 108. ... 154. 147. 149.]
  [122. 101. 101. ... 150. 145. 151.]
  ...
  [169. 172. 171. ... 167. 168. 184.]
  [172. 172. 171. ... 174. 161. 171.]
  [171. 169. 170. ... 178. 158. 164.]]

 [[117. 117. 119. ... 118. 117. 118.]
  [118. 119.

In [36]:
#Gabungkan data tersebut menjadi matriks data yang berukuran 50x12000
data = foto_mtr.reshape(50, 12000)
print(data.shape)

(50, 12000)


In [37]:
#Hitung matriks koragamannya
data_cov = np.cov(data)
print(data_cov)

[[ 1570.79868999 -1038.6907609    -68.45754782 ...  -112.61520637
     31.33247948   220.61700548]
 [-1038.6907609   6120.61363736  -363.51461688 ...   551.22001633
    418.39412107   217.86562858]
 [  -68.45754782  -363.51461688  2968.84129838 ...  -573.92990747
   1552.33203365  1028.22980267]
 ...
 [ -112.61520637   551.22001633  -573.92990747 ...  2250.47644914
   -652.84989893  -642.41377288]
 [   31.33247948   418.39412107  1552.33203365 ...  -652.84989893
   3360.84356996  2020.96129161]
 [  220.61700548   217.86562858  1028.22980267 ...  -642.41377288
   2020.96129161  2882.99594966]]


In [38]:
#Hitung vector ciri dan akar ciri dari matriks koragam tersebut
akarCiri, vektorCiri = np.linalg.eig(data_cov)
print(akarCiri)
print(vektorCiri)

[5.37394233e+04 2.46424213e+04 1.34115228e+04 1.01072748e+04
 8.22403046e+03 7.01140200e+03 4.55610429e+03 4.08817127e+03
 3.84259468e+03 3.57548964e+03 3.09513948e+03 2.52854114e+03
 2.43281955e+03 2.23955920e+03 2.02513626e+03 1.97986258e+03
 1.77317961e+03 1.48809681e+03 1.39477291e+03 1.33057107e+03
 1.29444877e+03 1.28141131e+03 1.19501139e+03 4.75761973e+01
 1.08523126e+03 1.02190670e+02 1.42983201e+02 1.49243418e+02
 1.84519974e+02 2.14238382e+02 2.29233382e+02 2.53822386e+02
 2.89503106e+02 3.33848446e+02 3.31007791e+02 3.73169576e+02
 3.93205041e+02 4.55266040e+02 5.03623225e+02 5.47909203e+02
 5.82494134e+02 6.15270406e+02 6.77486113e+02 7.64155970e+02
 9.77570774e+02 9.51663462e+02 8.14775550e+02 9.07906497e+02
 8.72224834e+02 8.69989337e+02]
[[ 0.01377069  0.11683256  0.06166879 ...  0.06595036 -0.18373715
   0.00259855]
 [-0.06742175 -0.33509476  0.13764424 ...  0.04631627 -0.02610147
   0.03574684]
 [-0.11552845  0.05855709 -0.11455145 ... -0.11059933 -0.04372007
  -0.050

In [39]:
#Tentukan banyaknya vector ciri yang akan diambil jika diinginkan proporsi informasi
# yang ditangkap oleh sumbu-sumbu baru adalah 90%
from sklearn.decomposition import PCA
data_pca = PCA(0.9)
data_pca.fit(data)
q_count = data_pca.n_components_
print(f"q yang diambil = {q_count}")

q yang diambil = 17


In [40]:
#Lakukan transformasi data asli yang berukuran 50x12000 menjadi data hasil transformasi yang berukuran 50xg (q adalah banyaknya sumbu baru yang dihasilkan
# dari point 8)
data_trans = data_pca.transform(data)
print(data_trans)

[[-3.75193459e+03 -2.97286844e+03 -1.17249193e+03 -3.66396463e+02
   1.17341214e+03 -1.65142432e+03 -8.19202466e+02  9.60007809e+01
  -1.23554170e+03 -6.73691397e+01 -2.23392157e+01 -8.10630928e+02
  -7.86758772e+02  3.39412434e+02  6.30265953e+02 -4.65329348e+02
  -3.21727864e+02]
 [-5.91731979e+03 -9.75110793e+02  6.63680921e+03  2.76822370e+03
  -2.02484232e+03  1.05872127e+03 -1.93626891e+03 -8.95285746e+01
  -1.04980241e+03  2.49416850e+03 -9.36588339e+02 -9.43150580e+02
  -6.15544938e+02 -9.81454060e+01 -4.72796151e+02  9.33363055e+02
  -4.27260157e+02]
 [ 2.94730382e+03  3.60402117e+03 -3.65326276e+02 -4.80228807e+02
  -5.58285942e+02 -7.46171116e+02  6.60970437e+01  1.35010639e+03
  -6.46150122e+02 -1.13754869e+03  1.04219150e+03 -8.75111445e+02
  -1.12992582e+03  6.91460088e+02 -1.15370648e+03  2.31658544e+03
   1.70706220e+03]
 [-3.33454156e+03 -2.34386243e+03 -2.11037810e+03 -2.63307640e+03
   5.30660757e+02 -1.47425318e+03 -3.51139532e+02  9.74326318e+02
   6.99977426e+01  

In [41]:
#Lakukan analisis klaster berdasar data hasil transformasi tersebut. Perhatikan
# anggota-anggota klaster jika diambil 10 klaster
from sklearn.cluster import KMeans
data_klaster = KMeans(n_clusters=10).fit(data_trans)
print(data_klaster.cluster_centers_)

[[ 5.74061694e+03  2.41935609e+03 -1.89880588e+02  7.45534639e+01
  -1.00969936e+03 -1.08994511e+03  6.85587845e+02  5.51281377e+02
   3.55084428e+02 -5.02047304e+02 -6.06929610e+02  7.26107077e+02
  -5.29351336e+02 -4.28465847e+01  1.48820569e+02  3.53214534e+02
  -5.12303437e+02]
 [-4.97704163e+03 -3.84728265e+03  2.84904239e+03 -3.38639020e+02
   2.31565554e+02 -1.17173974e+03  1.69998926e+03 -2.83175061e+02
  -8.51504471e+01 -5.16377606e+02  3.76523922e+01  4.55822446e+02
   1.64246317e+02  2.25610158e+01 -3.90658507e+02  5.48918122e+01
   1.16513306e+02]
 [ 4.21031492e+02  4.44851997e+03  2.14362990e+02  1.16159062e+02
  -4.95278441e+02 -8.33799556e+02 -8.31559689e+01 -2.97180027e+02
  -5.87011121e+02 -4.81100328e+01 -4.00372288e+00 -3.56415416e+02
   2.70050757e+02  1.04483566e+02 -7.99132775e+01 -4.45789149e+01
   2.92999337e+02]
 [-1.30142772e+02 -1.92573043e+03 -2.11343366e+03 -7.43051648e+01
  -3.37922559e+02 -1.22535289e+02 -1.19378332e+03 -7.89059682e+02
   6.84138341e+02 -